#web:
#  build: .
#  volumes:
#    - .:/champaign
#    - ../sou-assets:/sou-assets
#  ports:
#    - "3000:3000"
#  links:
#    - db
#    - redis
#  environment:
#    PG_USERNAME: postgres
#    PG_HOST: db
#  env_file:
#    - env.yml

db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: champaign

redis:
  image: redis
  ports:
    - "6379:6379"

